#!/bin/bash
# ---------------------------------------------------------------------------
# batch/htcondor/submit.sh -- submit HTCondor clusters (lxplus) that call
#                             scripts/run_job.sh, one job per file.
#
# Usage:
#   batch/htcondor/submit.sh <sample|all> <mass|all> [options]
#     --mode reco|ntuple     (default reco)
#     --range A-B            file indices (default 0-3999)
#     --max-running N        max_materialize: jobs in the queue at once (default 500)
#     --nevt N               events per file (default -1 = all)
#     --flavour F            +JobFlavour (default: longlunch for reco, espresso for ntuple)
#     --site S               site config (default lxplus)
#     --dry-run              write the submit files and print them, do not submit
#
# The repo must be on AFS (workers run scripts/run_job.sh from there) and the
# LCTuple build must exist (scripts/build_lctuple.sh on lxplus first).
# EOS access on the workers uses the Kerberos credential HTCondor forwards
# (MY.SendCredential); inputs and outputs move with xrdcp, see config/sites/lxplus.env.
#
# Logs: logs/condor/<mode>_<sample>_<mass>_<cluster>_<index>.{out,err,log}
# ---------------------------------------------------------------------------
set -euo pipefail
MTS_TAG=condor
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/common.sh"

MODE=reco; RANGE=0-3999; MAXRUN=500; NEVT=-1; SITE=lxplus; DRY=0; FLAVOUR=""; POS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --range) RANGE="$2"; shift 2 ;;
    --max-running) MAXRUN="$2"; shift 2 ;;
    --nevt) NEVT="$2"; shift 2 ;;
    --flavour) FLAVOUR="$2"; shift 2 ;;
    --site) SITE="$2"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    -h|--help) sed -n '2,23p' "$0"; exit 0 ;;
    -*) die "unknown option $1" ;;
    *) POS+=("$1"); shift ;;
  esac
done
[[ ${#POS[@]} -eq 2 ]] || die "usage: $0 <sample|all> <mass|all> [--mode reco|ntuple] [--range A-B] ..."
[[ "$MODE" == reco || "$MODE" == ntuple ]] || die "--mode must be reco or ntuple"
[[ "$RANGE" =~ ^([0-9]+)-([0-9]+)$ ]] || die "--range must look like 0-3999"
FIRST="${BASH_REMATCH[1]}"; LAST="${BASH_REMATCH[2]}"

if [[ "$MODE" == reco ]]; then CPUS=4; MEM=8GB; FLAVOUR="${FLAVOUR:-longlunch}"
else                           CPUS=1; MEM=4GB; FLAVOUR="${FLAVOUR:-espresso}"; fi

samples=("${POS[0]}"); [[ "${POS[0]}" == all ]] && samples=("${SAMPLES[@]}")
masses=("${POS[1]}");  [[ "${POS[1]}" == all ]] && masses=("${MASSES[@]}")

MTS_SITE="$SITE" mts_load_site
[[ "$DRY" == 1 ]] || mts_check_library

LOGDIR="$MTS_REPO/logs/condor"; mkdir -p "$LOGDIR"
for s in "${samples[@]}"; do
  for m in "${masses[@]}"; do
    mts_check_sample "$s" "$m"
    tag="${MODE}_${s}_${m}"
    sub="$LOGDIR/$tag.sub"
    cat > "$sub" <<EOF
# generated by batch/htcondor/submit.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
universe              = vanilla
executable            = $MTS_REPO/batch/htcondor/job.sh
arguments             = $s $m \$(MTS_INDEX) --mode $MODE --nevt $NEVT
environment           = "MTS_REPO_DIR=$MTS_REPO MTS_SITE=$SITE"
getenv                = False
output                = $LOGDIR/${tag}_\$(ClusterId)_\$(MTS_INDEX).out
error                 = $LOGDIR/${tag}_\$(ClusterId)_\$(MTS_INDEX).err
log                   = $LOGDIR/${tag}_\$(ClusterId).log
request_cpus          = $CPUS
request_memory        = $MEM
+JobFlavour           = "$FLAVOUR"
MY.SendCredential     = True
max_materialize       = $MAXRUN
on_exit_hold          = (ExitCode != 0)
queue MTS_INDEX from seq $FIRST 1 $LAST |
EOF
    if [[ "$DRY" == 1 ]]; then echo "### $sub"; cat "$sub"; else condor_submit "$sub"; fi
  done
done
